Rscript run_hier_model_multivariate.R mturk
Rscript run_hier_model_multivariate.R legal
Rscript run_hier_model_multivariate.R lsba
Rscript run_hier_model_multivariate.R ilsa
Rscript postprocess_stan_hier_multi_data.R
